// Recipes
export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES'
export const SET_SEARCHED_ESTABLISHMENTS = 'SET_SEARCHED_ESTABLISHMENTS'
export const SET_RATING = 'SET_RATING'
export const SET_COORDS = 'SET_COORDS'



// Navigation
export const SET_TAB = 'SET_TAB'

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'
